package de.viasurance.kfzglasbruch.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

import de.viasurance.model.Kontoverbindung;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebService(name = "PartnersystemWebService", targetNamespace = "http://ws.partnersystem.viasurance.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PartnersystemWebService {

    @WebMethod
    @WebResult(name = "kontoverbindung", partName = "kontoverbindung")
    @Action(input = "http://ws.partnersystem.viasurance.de/PartnersystemWebService/getKontoverbindungByKundennummerRequest", output = "http://ws.partnersystem.viasurance.de/PartnersystemWebService/getKontoverbindungByKundennummerResponse")
    public Kontoverbindung getKontoverbindungByKundennummer(
            @WebParam(name = "kundennummer", partName = "kundennummer") String kundennummer);
}