package de.viasurance.kfzglasbruch.wsclient;

import java.net.MalformedURLException;
import java.net.URL;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;



/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Partnersystem", targetNamespace = "http://ws.partnersystem.viasurance.de/", wsdlLocation = "http://localhost:8080/viasurance-webservices-0.9.0/partnersystem?wsdl")
public class Partnersystem extends Service {

    private final static URL PARTNERSYSTEM_WSDL_LOCATION;

    private final static WebServiceException PARTNERSYSTEM_EXCEPTION;

    private final static QName PARTNERSYSTEM_QNAME = new QName("http://ws.partnersystem.viasurance.de/",
            "Partnersystem");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/viasurance-webservices-0.9.0/partnersystem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTNERSYSTEM_WSDL_LOCATION = url;
        PARTNERSYSTEM_EXCEPTION = e;
    }

    public Partnersystem() {
        super(__getWsdlLocation(), PARTNERSYSTEM_QNAME);
    }

    public Partnersystem(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERSYSTEM_QNAME, features);
    }

    public Partnersystem(URL wsdlLocation) {
        super(wsdlLocation, PARTNERSYSTEM_QNAME);
    }

    public Partnersystem(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERSYSTEM_QNAME, features);
    }

    public Partnersystem(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Partnersystem(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns PartnersystemWebService
     */
    @WebEndpoint(name = "PartnersystemWebServicePort")
    public PartnersystemWebService getPartnersystemWebServicePort() {
        return super.getPort(new QName("http://ws.partnersystem.viasurance.de/", "PartnersystemWebServicePort"),
                PartnersystemWebService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return returns PartnersystemWebService
     */
    @WebEndpoint(name = "PartnersystemWebServicePort")
    public PartnersystemWebService getPartnersystemWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.partnersystem.viasurance.de/", "PartnersystemWebServicePort"),
                PartnersystemWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERSYSTEM_EXCEPTION != null) {
            throw PARTNERSYSTEM_EXCEPTION;
        }
        return PARTNERSYSTEM_WSDL_LOCATION;
    }
}