package de.viasurance.kfzglasbruch.wsclient;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Vertragssystem", targetNamespace = "http://ws.vertragssystem.viasurance.de/", wsdlLocation = "http://localhost:8080/viasurance-webservices-0.9.0/vertragssystem?wsdl")
public class Vertragssystem extends Service {

    private final static URL VERTRAGSSYSTEM_WSDL_LOCATION;

    private final static WebServiceException VERTRAGSSYSTEM_EXCEPTION;

    private final static QName VERTRAGSSYSTEM_QNAME = new QName("http://ws.vertragssystem.viasurance.de/",
            "Vertragssystem");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/viasurance-webservices-0.9.0/vertragssystem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERTRAGSSYSTEM_WSDL_LOCATION = url;
        VERTRAGSSYSTEM_EXCEPTION = e;
    }

    public Vertragssystem() {
        super(__getWsdlLocation(), VERTRAGSSYSTEM_QNAME);
    }

    public Vertragssystem(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERTRAGSSYSTEM_QNAME, features);
    }

    public Vertragssystem(URL wsdlLocation) {
        super(wsdlLocation, VERTRAGSSYSTEM_QNAME);
    }

    public Vertragssystem(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERTRAGSSYSTEM_QNAME, features);
    }

    public Vertragssystem(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Vertragssystem(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns VertragssystemWebService
     */
    @WebEndpoint(name = "VertragssystemWebServicePort")
    public VertragssystemWebService getVertragssystemWebServicePort() {
        return super.getPort(new QName("http://ws.vertragssystem.viasurance.de/", "VertragssystemWebServicePort"),
                VertragssystemWebService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return returns VertragssystemWebService
     */
    @WebEndpoint(name = "VertragssystemWebServicePort")
    public VertragssystemWebService getVertragssystemWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.vertragssystem.viasurance.de/", "VertragssystemWebServicePort"),
                VertragssystemWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERTRAGSSYSTEM_EXCEPTION != null) {
            throw VERTRAGSSYSTEM_EXCEPTION;
        }
        return VERTRAGSSYSTEM_WSDL_LOCATION;
    }
}