package de.viasurance.kfzglasbruch.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

import de.viasurance.model.Vertrag;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebService(name = "VertragssystemWebService", targetNamespace = "http://ws.vertragssystem.viasurance.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface VertragssystemWebService {

    @WebMethod
    @WebResult(name = "vertrag", partName = "vertrag")
    @Action(input = "http://ws.vertragssystem.viasurance.de/VertragssystemWebService/getVertragByVsnrRequest", output = "http://ws.vertragssystem.viasurance.de/VertragssystemWebService/getVertragByVsnrResponse")
    public Vertrag getVertragByVsnr(@WebParam(name = "vsnr", partName = "vsnr") String vsnr);
}